### ISSUE TITLE
fin usb hub driver not respecting uhubcitl commands

### ISSUE THREAD

**Issue by rcooke-warwick** [balena-io-hardware/testbotsdk#27]
noted here: 

https://github.com/balena-io-hardware/balena-fulfillment-rig/blob/master/core/app/utils/dut-power/index.js#L26
When toggling the state of the usb port connected to the fin DUT while flashing it, the hub sometimes doesn't respect the uhubctl command (reportedly)

We have been having problems with provisioning fins using the testbotsdk - this could be related.

**Comment by Bucknalla** [comment]
We should be doing [this](https://github.com/balena-io-hardware/testbotsdk/pull/26#discussion_r808732067) in accordance to a suggestion from uhubctl maintainer to use `-r 1000` instead of the command twice.

**Comment by Bucknalla** [comment]
This was resolved in #28
